### ISSUE TITLE
Hard-coded Referrer Causes Fetch Error in Worker

### ISSUE THREAD

**Issue by solaris007** [adobe/alloy#936]
### Expected Behaviour

When alloy is served via a worker (`WorkerGlobalScope`), the tracking request sent via `injectSendFetchRequest` should be successfully passed to the network stack.

### Actual Behavior

The tracking request is aborted due to:
```
Uncaught (in promise) TypeError: [alloy] [DataCollector] An error occurred while executing the sendEvent command.
Caused by: Network request failed.
Caused by: Failed to execute 'fetch' on 'WorkerGlobalScope': Referrer 'client' is not a valid URL.
    at fetch (787bcdb0-6c08-4442-9830-5c5151bd24a0:2:18168)
    at injectSendFetchRequest (alloy.js:8694:14)
    at executeRequest (alloy.js:3182:16)
    at injectSendNetworkRequest (alloy.js:3224:14)
    at eval (alloy.js:9224:16)
```

It seems that the Fetch API performs Referrer validation (valid URL) when called via a web worker. The relevant possible `TypeError` is listed on the Fetch API doc: https://developer.mozilla.org/en-US/docs/Web/API/fetch#exceptions

### Reproduce Scenario (including but not limited to)

Embed alloy in a worker via `partytown` (https://partytown.builder.io) and send test event:
```
<script>
  partytown = {
    lib: '/scripts/',
    forward: [
      '__alloyMonitors',
      '__alloyNS',
      'alloy',
      'alloy_all',
      'alloy_click',
      'alloy_last_event',
      'alloy_load',
      'alloy_unload',
      'adobe',
    ]
  };
</script>
<script src="/scripts/partytown.js"></script>

<script type="text/partytown">
  !function(n,o){o.forEach(function(o){n[o]||((n.__alloyNS=n.__alloyNS||
    []).push(o),n[o]=function(){var u=arguments;return new Promise(
    function(i,l){n[o].q.push([i,l,u])})},n[o].q=[])})}
  (window,["alloy"]);
</script>
<script type="text/partytown" src="/scripts/alloy.js" async></script>
<script type="text/partytown">
    alloy("configure", {
      "edgeConfigId": "<some-dataset-id>",
      "orgId":"<some-org-id>"
    });
    alloy("sendEvent", {
      data: {
        myNameSpace: {
            init: true,
        }
      }
    });

</script>
```

#### Steps to Reproduce
- Load Page
- Observe dev tools JS console

#### Platform and Version
alloy 2.13.1 / static HTML test site.

#### Sample Code that illustrates the problem

See reproduce scenario

**Comment by solaris007** [comment]
https://github.com/adobe/alloy/pull/937
